apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-init-db
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: jobs-init-db
        image: {{ jobs_postgres16_image }}
        imagePullPolicy: Always
        command: ["/tmp/jobs-init-db-sh"]
        volumeMounts:
        - name: jobs-init-db-vol
          mountPath: /tmp
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: postgres-password
        - name: TAPIS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: tapis-postgres-password
        - name: MONITOR_PASSWORD
          value: 60f0c5bf8ed23120fc60
      volumes:
      - name: jobs-init-db-vol
        configMap:
          name: jobs-init-db-configmap
          defaultMode: 0777
  backoffLimit: 4
