apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-datasets-api-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-datasets-api-deployment
  template:
    metadata:
      labels:
        app: mlhub-datasets-api-deployment
    spec:
      containers:
      - env:
          - name: DB_HOST
            value: mlhub-postgres-service
          - name: DB_NAME
            value: mlhub
          - name: DB_PASSWORD
            value: dev
          - name: DB_USER
            value: mlhub
          - name: RUST_LOG
            value: debug
          - name: SHARED_DATA
            value: /srv/mlub
        image: tapis/datasets-api:local
        imagePullPolicy: Always
        name: mlhub-datasets-api
        ports:
          - containerPort: 8000
            name: webserver
        resources: {}
        tty: true
        volumeMounts:
              - name: nfs-server-mount
                mountPath: /srv/mlhub/
      volumes:
        - name: nfs-server-mount
          nfs:
            server: '** NFS_SERVER_COMPONENT_IP **'
            path: /