apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-nfs-server-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-nfs-server-deployment
  template:
    metadata:
      labels:
        app: mlhub-nfs-server-deployment
    spec:
      initContainers:
      - name: create-mount-dirs
        image: busybox
        command: ["sh", "-c", "mkdir -p /nfsshare/mlhub/models /nfsshare/mlhub/datasets /nfsshare/mlhub/inference /nfsshare/mlhub/training"]
      containers:
      - name: mlhub-nfs-server
<<<<<<< HEAD
        image: {{mlhub_nfs_server_image}}
=======
        image: {{ mlhub_nfs_image }}
>>>>>>> mlhub
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: "/nfsshare"
        ports:
        - name: nfs
          containerPort: 2049
        volumeMounts:
        - name: nfs-data
          mountPath: "/nfsshare"
        resources: {}
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: mlhub-nfs-server-pvc

