
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlhub-nfs-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
<<<<<<< HEAD
  storageClassName: {{ mlhub_storage_class }}
=======
  storageClassName: standard
>>>>>>> mlhub
  resources:
    requests:
      storage: 20Gi