
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlhub-nfs-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ mlhub_storage_class }}
  resources:
    requests:
      storage: 200Gi