---
mlhub_models_api_image: tapis/models-api:25Q4.0
mlhub_datasets_api_image: tapis/datasets-api:25Q4.0
mlhub_inference_api_image: tapis/inference-api:25Q4.0
mlhub_training_api_image: tapis/training-api:25Q4.0
mlhub_nfs_server_image: itsthenetwork/nfs-server-alpine:latest
mlhub_traefik_image: traefik:v3.2
mlhub_artifact_ingester_image: tapis/mlhub-artifact-ingester:25Q4.0
mlhub_artifact_publisher_image: tapis/mlhub-artifact-publisher:25Q4.0
mlhub_artifact_db_image: mongo:8.0.13
mlhub_artifact_mq_image: rabbitmq:3.9.11-management
