---
mlhub_models_api_image: tapis/models-api:dev
mlhub_datasets_api_image: tapis/datasets-api:dev
mlhub_inference_api_image: tapis/inference-api:dev
mlhub_training_api_image: tapis/training-api:dev
mlhub_nfs_server_image: itsthenetwork/nfs-server-alpine:latest
mlhub_traefik_image: traefik:v3.2