meta_api_image: tapis/metaapi:25Q4.0
meta_rh_server_image: tapis/tapis-meta-rh-server:25Q4.0
meta_mongo_exporter_image: tapis/mqe:25Q4.0
meta_mongo_singlenode_image: tapis/mongo-singlenode:25Q4.0
meta_mongodb_backup_image: tapis/mongodb-backup:25Q4.0
meta_mongobackup_image: tapis/mongobackup:25Q4.0
meta_alpine_image: alpine:3.17
meta_util_image: tapis/ubutil2204:25Q4.0
