files_api_image: tapis/tapis-files:1.5.0
files_workers_image: tapis/tapis-files-workers:1.5.0
files_postgres_image: postgres:11
files_migrations_image: postgres:11
files_minio_image: minio/minio
files_irods_provider_postgres_image: mjstealey/irods-provider-postgres:4.2.4
files_pgadmin_image: dpage/pgadmin4:6.20
files_rabbitmq_image: rabbitmq:3.8.11-management
files_rabbitmq_management_image: rabbitmq:3-management-alpine
files_util_image: tapis/ubutil2204:1.5.0
