apiVersion: v1
kind: ConfigMap
metadata:
  name: mlhub-cm-init-artifact-db-script
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    attempt=0
    until mongosh "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/admin" --eval "db.runCommand({ ping: 1 })"; do
      echo "Attempting to connect to the db. Attempt: $attempt"
      sleep 1
      attempt=$((attempt + 1))
      if [ "$attempt" -eq 15 ]; then
        echo "Failed to connect to database"
        exit 1
      fi
    done

    mongosh "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/admin" --eval "
      if (!db.getUser('${MLHUB_USERNAME}')) {
        db.createUser({
          user: '${MLHUB_USERNAME}',
          pwd: '${MLHUB_PASSWORD}',
          roles: [{ role: 'readWrite', db: 'mlhub' }]
        });
        print('User created.');
      } else {
        print('User already exists, skipping.');
      }
    "
    
    echo $?