apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-models-api-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-models-api-deployment
  template:
    metadata:
      labels:
        app: mlhub-models-api-deployment
    spec:
      containers:
        - env:
            - name: ARTIFACTS_DB_HOST
              value: mlhub-artifact-db-service
            - name: ARTIFACTS_DB_PORT
              value: "27017"
            - name: ARTIFACTS_DB_NAME
              value: mlhub
            - name: ARTIFACTS_DB_PASSWORD
              value: password
            - name: ARTIFACTS_DB_USERNAME
              value: mlhub
            - name: ARTIFACT_OP_MQ_HOST
              value: mlhub-artifact-mq-service
            - name: ARTIFACT_OP_MQ_PASSWORD
              value: dev
            - name: ARTIFACT_OP_MQ_PORT
              value: "5672"
            - name: ARTIFACT_OP_MQ_USER
              value: dev
            - name: RUST_LOG
              value: debug
            - name: SHARED_DATA
              value: /srv/mlhub
          image: tapis/models-api:local
          imagePullPolicy: Never
          name: models-api
          ports:
            - containerPort: 8000
              name: webserver
          # readinessProbe:
          #   httpGet:
          #     path: /models-api/health-check
          #     port: 8000
          #   initialDelaySeconds: 2
          #   periodSeconds: 15
          #   failureThreshold: 5

          resources: {}
          tty: true
          volumeMounts:
              - name: nfs-server-mount
                mountPath: /srv/mlhub/
      volumes:
        - name: nfs-server-mount
          nfs:
            server: '{{ NFS_SERVER_COMPONENT_IP }}'
            path: /