---

pods_service_name: pods
pods_image_version: 1.7.0
pods_service_site_id: "{{ global_site_id }}"
pods_service_tenant_id: admin
pods_primary_site_admin_tenant_base_url: "{{ global_primary_site_admin_tenant_base_url }}"
pods_image_pull_policy: Always
pods_pvc_storage_class_name: "{{ global_storage_class }}"
pods_postgres_pvc: pods-postgres-vol01
pods_rabbitmq_pvc: pods-rabbitmq-vol01
pods_storage_class: "{{ global_storage_class }}"
pods_log_level: INFO
pods_traefik_certs_file: null
pods_traefik_cert_key: null
pods_image_allow_list: 
  - alpine:3.17
pods_spawner_host_queues: 
  - quick


