apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-training-api-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-training-api-deployment
  template:
    metadata:
      labels:
        app: mlhub-training-api-deployment
    spec:
      containers:
      - env:
          - name: DB_HOST
            value: mlhub-postgres-service
          - name: DB_NAME
            value: mlhub
          - name: DB_PASSWORD
            value: dev
          - name: DB_USER
            value: mlhub
          - name: RUST_LOG
            value: debug
        image: {{ mlhub_training_api_image }}
        imagePullPolicy: Always
        name: mlhub-training-api
        ports:
          - containerPort: 8000
            name: webserver
        resources: {}
        tty: true