streams_alpine_image: alpine:3.17
streams_influxdb1_image: influxdb:1.7.7
streams_influxdb2_image: influxdb:2.1.1-alpine
streams_mysql_image: mysql:5.7
streams_chords_image: ncareol/chords:1.0
streams_tapis_chords_app_image: scleveland/tapis-chords-app:0.9.8.2.3
streams_api_image: tapis/streams-api:1.5.0
streams_util_image: tapis/ubutil2204:1.5.0
