skadmin_securityexport_image: tapis/securityexport:1.6.0
skadmin_skadminutil_image: tapis/skadminutil:1.6.0
skadmin_securityadmin_image: tapis/securityadmin:1.6.0
skadmin_util_image: tapis/ubutil:1.6.0
