---

skadmin_service_name: skadmin
skadmin_service_site_id: "{{ global_site_id }}"
skadmin_service_url: "{{ global_service_url }}"
skadmin_service_tenant_id: admin
skadmin_vault_url: "{{ global_vault_url }}"
skadmin_passwords: true
skadmin_image_pull_policy: Always
skadmin_initLoad_jwtsigning_tenants:
  - admin
  - dev

# Set this to a different service account name (other than your default) to be used for for certain sk processes.
# This service account should be created in Kubernetes outside of Tapis Deployer.
skadmin_sk_privileged_sa: null



