apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-rdr-altqueue
spec:
  selector:
    matchLabels:
      app: jobrdr
  template:
    metadata:
      labels:
        app: jobrdr
    spec:
      initContainers:
      automountServiceAccountToken: false
      containers:
      - name: jobs-rdr-altqueue
        image: {{ jobs_worker_image }}
        imagePullPolicy: Always
        env:
        - name: TAPIS_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: site_id
        - name: TAPIS_TENANT_SVC_BASEURL
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: service_site_url
        - name: TAPIS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: service-password
        - name: TAPIS_DB_CONNECTION_POOL_SIZE
          value: "2"
        - name: TAPIS_DB_USER
          value: "tapis"
        - name: TAPIS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: tapis-postgres-password
        - name: TAPIS_DB_JDBC_URL
          value: "jdbc:postgresql://jobs-postgres-16:5432/tapisjobsdb?ApplicationName=jobsaltq"
        - name: TAPIS_QUEUE_HOST
          value: jobs-rabbitmq
        - name: TAPIS_QUEUE_ADMIN_USER
          value: "tapis"
        - name: TAPIS_QUEUE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-tapis-password
        - name: TAPIS_QUEUE_USER
          value: "jobs"
        - name: TAPIS_QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-jobs-password
        - name: TAPIS_REQUEST_LOGGING_FILTER_PREFIXES
          value: "/v3/jobs"
        - name: JAVA_OPTS 
          value: "-Xms1g -Xmx1g"
        - name: MAIN_CLASS
          value: "edu.utexas.tacc.tapis.jobs.reader.AltQueueReader"
        - name: JOBS_PARMS
          value: "-n rdr-alt"
