workflows_api_image: tapis/workflows-api:1.3.0
workflows_pipelines_image: tapis/workflows-pipelines:1.3.0
workflows_engine_streams_image: tapis/workflow-engine-streams:1.3.0
workflows_mysql_image: mysql:8
workflows_rabbitmq_image: rabbitmq:3.9.11-management
workflows_registry_image: registry:2
workflows_nfs_server_image: itsthenetwork/nfs-server-alpine:12
