kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlhub-artifact-mq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  {{ mlhub_storage_class }}
  resources:
    requests:
      storage: 10Gi