apiVersion: v1
kind: Service
metadata:
  name: mlhub-traefik

spec:
  selector:
    app: mlhub-traefik
  ports:
    - targetPort: mlhub-traefik
      port: 80
      targetPort: web

#--- 
#apiVersion: v1
#kind: Service
#metadata:
#  name: traefik-dashboard-service

#spec:
#  selector:
#    app: mlhub-traefik
#  type: LoadBalancer
#  ports:
#    - port: 8080
#      targetPort: dashboard
