tenants_pgadmin_image: dpage/pgadmin4:6.20
tenants_postgres_image: postgres:11.4
tenants_api_image: tapis/tenants-api:25Q4.0
tenants_migrations_image: tapis/tenants-api-migrations:25Q4.0
tenants_api_tests_image: tapis/tenants-api-tests:25Q4.0
tenants_util_image: tapis/ubutil2204:25Q4.0
