---

apps_service_name: apps
apps_service_site_id: "{{ global_site_id }}" 
apps_service_tenant_id: admin
apps_service_url: "{{ global_service_url }}"
apps_storage_class: "{{ global_storage_class }}"
apps_enable_external: false
apps_monitor_password: null
apps_postgres_pvc: apps-postgres-vol01
apps_service_password: null
apps_postgres_password: null
apps_pgadmin_password: null
apps_heap_min: 1g
apps_heap_max: 4g

